### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [monzorg/firefighter-robot#1]
When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. There is no need to wait for something after the Wire.requestFrom().

The while-loop after the Wire.requestFrom() to wait for something can be removed in these files:
firefighter-robot/firmware/tpa81.cpp  (once)
firefighter-robot/firmware/compass.cpp  (once, in uread)

**Comment by FFY00** [comment]
Quickly updated it. Check it out and tell me if I can close the pull request.

**Comment by Koepel** [comment]
Yes, it's okay now.
